# Generated by Django 5.2.3 on 2025-06-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_app', '0004_highlight_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='note',
        ),
        migrations.AddField(
            model_name='highlight',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='position_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
