# Generated by Django 5.2.3 on 2025-06-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_app', '0005_remove_highlight_note_highlight_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
